"""Add deleted column to location table

Revision ID: 013386b4209d
Revises: 98b65a6b5103
Create Date: 2025-10-03 10:30:00.066019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013386b4209d'
down_revision = '98b65a6b5103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True, default=False))
    
    # Set default value for existing records
    connection = op.get_bind()
    connection.execute("UPDATE location SET deleted = false WHERE deleted IS NULL")
    
    # Make the column non-nullable after setting defaults
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('deleted')
    # ### end Alembic commands ###
