"""Auto-generated migration

Revision ID: 06b2f2a91947
Revises: simple_add_location_deleted
Create Date: 2025-10-04 08:02:02.598152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b2f2a91947'
down_revision = 'simple_add_location_deleted'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clergy_ordaining_bishop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('clergy_consecrator_id_fkey'), type_='foreignkey')
        batch_op.drop_column('date_of_ordination')
        batch_op.drop_column('co_consecrators')
        batch_op.drop_column('ordaining_bishop_id')
        batch_op.drop_column('consecrator_id')
        batch_op.drop_column('date_of_consecration')

    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.alter_column('is_bishop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.alter_column('is_bishop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_consecration', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consecrator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ordaining_bishop_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_consecrators', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_ordination', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('clergy_consecrator_id_fkey'), 'clergy', ['consecrator_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('clergy_ordaining_bishop_id_fkey'), 'clergy', ['ordaining_bishop_id'], ['id'])

    # ### end Alembic commands ###
