"""add_is_bishop_field_to_rank_table

Revision ID: 2a3813314646
Revises: 4c4903a27386
Create Date: 2025-09-15 11:12:39.449398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3813314646'
down_revision = '4c4903a27386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bishop', sa.Boolean(), nullable=False, server_default='false'))
    
    # Update existing ranks to set is_bishop based on name
    op.execute("""
        UPDATE rank 
        SET is_bishop = true 
        WHERE LOWER(name) LIKE '%bishop%' 
        OR LOWER(name) LIKE '%pope%' 
        OR LOWER(name) LIKE '%archbishop%' 
        OR LOWER(name) LIKE '%cardinal%'
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.drop_column('is_bishop')

    # ### end Alembic commands ###
