"""Add Location table for geographic plotting

Revision ID: 59721b60a4a4
Revises: 2f11157c9eef
Create Date: 2025-10-01 22:17:41.582131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59721b60a4a4'
down_revision = '2f11157c9eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
