"""Auto-generated migration

Revision ID: 677af5ab3c7e
Revises: 8ce8b81669c9
Create Date: 2025-10-03 12:51:29.638794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677af5ab3c7e'
down_revision = '8ce8b81669c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
