"""Add image_url field to clergy table

Revision ID: 8cd1c86c2ec4
Revises: bc170867dac1
Create Date: 2025-08-27 09:02:04.477001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd1c86c2ec4'
down_revision = 'bc170867dac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
