"""Auto-generated migration

Revision ID: 8ce8b81669c9
Revises: 013386b4209d
Create Date: 2025-10-03 10:31:42.167185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce8b81669c9'
down_revision = '013386b4209d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_invite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clergy_ordaining_bishop_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('clergy_consecrator_id_fkey'), type_='foreignkey')
        batch_op.drop_column('ordaining_bishop_id')
        batch_op.drop_column('consecrator_id')
        batch_op.drop_column('co_consecrators')
        batch_op.drop_column('date_of_consecration')
        batch_op.drop_column('date_of_ordination')

    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.alter_column('is_bishop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rank', schema=None) as batch_op:
        batch_op.alter_column('is_bishop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_ordination', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_consecration', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_consecrators', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('consecrator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ordaining_bishop_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('clergy_consecrator_id_fkey'), 'clergy', ['consecrator_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('clergy_ordaining_bishop_id_fkey'), 'clergy', ['ordaining_bishop_id'], ['id'])

    with op.batch_alter_table('admin_invite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
