"""Add image_data field to clergy table for multiple image sizes

Revision ID: 9eed07e44dd1
Revises: 8cd1c86c2ec4
Create Date: 2025-08-27 09:13:44.306812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eed07e44dd1'
down_revision = '8cd1c86c2ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    # Get connection to check existing columns
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Check if clergy table exists and add column if it doesn't exist
    tables = inspector.get_table_names()
    if 'clergy' in tables:
        clergy_columns = [col['name'] for col in inspector.get_columns('clergy')]
        
        if 'image_data' not in clergy_columns:
            with op.batch_alter_table('clergy', schema=None) as batch_op:
                batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))
        else:
            print("⚠️  Column 'image_data' already exists in clergy table")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
