"""Add image_data field to clergy table for multiple image sizes

Revision ID: 9eed07e44dd1
Revises: 8cd1c86c2ec4
Create Date: 2025-08-27 09:13:44.306812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eed07e44dd1'
down_revision = '8cd1c86c2ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clergy', schema=None) as batch_op:
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
