services:
  - type: web
    name: ecclesiastical-lineage
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x scripts/deploy/deploy_flask_migrate_proper.sh && ./scripts/deploy/deploy_flask_migrate_proper.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecclesiastical-lineage-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: FLASK_ENV
        value: production
      - key: PRODUCTION_API_URL
        value: https://ecclesiastical-lineage.onrender.com/clergy/lineage-data

databases:
  - name: ecclesiastical-lineage-db
    plan: free
    databaseName: ecclesiastical_lineage
    user: ecclesiastical_lineage_user
